### ISSUE TITLE
1.1.2 MaximumPasswordAge validate range

### ISSUE THREAD

**Issue by progmatic73** [techservicesillinois/SecOps-Powershell-CISDSC#204]
**Describe the bug**
Question:
CIS Benchmark for Windows Server 2019: 1.1.2 Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'
Supplying parameter cis112MaximumPasswordAge = 30 fails since the param has [ValidateRange(60,999)]
Shouldn't the range be (1,60)?

**To Reproduce**
1. Supply parameter 'cis112MaximumPasswordAge = 30' to 'CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809' resource.
2. Error:
"PSDesiredStateConfiguration\node : The 30 argument is less than the minimum allowed range of 60. Supply an argument that is greater than or equal to 60 and then try the 
command again."

**Expected behavior**
Able to supply value from 1 to 60 for cis112MaximumPasswordAge.

**Screenshots**
![image](https://user-images.githubusercontent.com/11061246/122391463-080fa900-cf41-11eb-835b-aacca1129aff.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - PowerShell Version 5.1

**Additional context**

**Comment by MKletz** [comment]
@progmatic73  Thanks for reaching out. After reviewing the CIS documentation this is indeed an incorrect validate range. The fix is included in #205 and should be released to the gallery in the very near future.

**Comment by MKletz** [comment]
@progmatic73 v2.4.0 is available on the gallery with this fix

**Comment by progmatic73** [comment]
@MKletz Awesome! Thanks for the quick work!
