### ISSUE TITLE
CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809 - 18.3.6 mismatch with latest v1.2.1 CIS benchmark

### ISSUE THREAD

**Issue by andes2020** [techservicesillinois/SecOps-Powershell-CISDSC#246]
v1.2.0 and v.1.2.1 (latest) benchmark document : 18.3.6 (L1) Ensure 'WDigest Authentication' is set to 'Disabled'

v1.1.0: (L1) 18.3.6 (L1) Ensure 'NetBT NodeType configuration' is set to 'Enabled: P-node (recommended)' (Scored)

Is it meant to match v1.1.0 document only?

<img width="1559" alt="Screenshot 2022-03-04 112945" src="https://user-images.githubusercontent.com/74114151/156755775-a5fd564b-10a1-46c1-8ae4-459e60d6be38.png">

**Comment by edthedev** [comment]
> Is it meant to match v1.1.0 document only?

@andes2020 Latest benchmarks are generally our desired target, but it's certainly possible we're not updated for a given benchmark. Pull requests are always welcome.

Can you add the full name of the benchmark you're working with to this issue to facilitate discussion?

Thanks!

**Comment by andeslam** [comment]
[CIS_Microsoft_Windows_Server_2019_Benchmark_v1.2.1.pdf](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/files/8186907/CIS_Microsoft_Windows_Server_2019_Benchmark_v1.2.1.pdf)
@edthedev

**Comment by MKletz** [comment]
What you provided is indeed a newer revision to the benchmark than what we have in use. There is indeed a mapping between benchmark number and resource number. The resource is V1.1.1.1 which means benchmark V1.1.1 with 1 bug fix on our end. We'll take a look.
