### ISSUE TITLE
Website in documentation no longer SFW

### ISSUE THREAD

**Issue by kbrady-cmd** [techservicesillinois/SecOps-Powershell-CISDSC#251]
The website https://getadmx.com/ as mentioned in the static_corrections [document](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/blob/main/docs/static_corrections.md) seems to no longer exist as a technical resource and is not SFW

**Comment by MKletz** [comment]
oh my god you're not wrong we will get that corrected @baristaTam
