### ISSUE TITLE
Add Windows 11 Resource

### ISSUE THREAD

**Issue by baristaTam** [techservicesillinois/SecOps-Powershell-CISDSC#266]
Is your feature request related to a problem? Please describe.
Lacking support for an OS

Describe the solution you'd like

## Tasks

- [x] #267
- [x] Add resources for Windows 11
- [x] update the CHANGELOG

**Comment by baristaTam** [comment]
The static corrections have all been addressed in the static corrections file. However, when attempting to generate the resource, there are 6 warnings about registry keys that are definitely in Win11_23H2_corrections.csv. We expect no warnings about these registry keys. 

WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\FVE:FDVAllowSoftwareEncryptionFailover.
WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\AppHVSI:AppHVSIClipboardFileType.
WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging:EnableScriptBlockInvocationLogging.
WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription:OutputDirectory.
WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription:EnableInvocationHeader.
WARNING: Failed to find a recommendation for Registry HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\WCN\Registrars:MaxWCNDeviceNumber.

**Comment by baristaTam** [comment]
When attempting to generate the WIN 11 23H2 resource, multiple errors related to null keys and null hashtables.


InvalidOperation: C:\Users\buch1\OneDrive - University of Illinois - Urbana\code\SecOps-Powershell-CISDSC\src\CISDSCResourceGeneration\functions\private\ConvertFrom-SystemAccessRawGPO.ps1:43:13
Line |
  43 |              $SecuritySetting = $ValueData
     |              ~~~~~~~~~~~~~~~~
     | A null key is not allowed in a hash literal.

>> TerminatingError(Get-RecommendationFromGPOHash): "Cannot bind argument to parameter 'GPOHash' because it is null."

Get-RecommendationFromGPOHash: C:\Users\buch1\OneDrive - University of Illinois - Urbana\code\SecOps-Powershell-CISDSC\src\CISDSCResourceGeneration\functions\private\ConvertFrom-SystemAccessRawGPO.ps1:47:69
Line |
  47 |  … um = Get-RecommendationFromGPOHash -GPOHash $SystemAccessHash -Type ' …
     |                                                ~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'GPOHash' because it is null.

**Comment by baristaTam** [comment]
The static corrections issue has been fixed. The keys in question were not mapped to real recommendations in the actual benchmark. We did the corrections as a group and pasting back and forth between files. In most cases the recommendation number was left set to the Win 10 value accidentally. Chalk it up to human error. The null key issue is the only one that remains.

**Comment by baristaTam** [comment]
System Access subkey: AllowAdministratorLockout with value '1' seems to be the key causing all the null value errors.
In ConvertFrom-SystemAccessRawGPO the subkey gets passed in as $key, so 'AllowAdministratorLockout' is the key in this case. In this function it checks if that key is in the $script:SecurityOptionSettings.Keys or $script:AccountPolicySettings.keys and 'AllowAdministratorLockout' is the only one in neither. For future-proofing this should probably error if it doesn't enter either if statement. 

    if($script:SecurityOptionSettings.ContainsKey($Key)){
            $SecuritySetting = $script:SecurityOptionSettings[$key]
            $ResourceName = "SecurityOption"
        }
        elseif($script:AccountPolicySettings.ContainsKey($Key)){
            $SecuritySetting = $script:AccountPolicySettings[$key]
            $ResourceName = "AccountPolicy"
        }

They actual keys present in these two script context variables are:

EnableGuestAccount NewAdministratorName ForceLogoffWhenHourExpire LSAAnonymousNameLookup EnableAdminAccount NewGuestName
and
ClearTextPassword MaxRenewAge MaximumPasswordAge MaxTicketAge MaxClockSkew TicketValidateClient PasswordComplexity LockoutBadCount MaxServiceAge LockoutDuration MinimumPasswordAge MinimumPasswordLength ResetLockoutCount PasswordHistorySize

Will need to keep working backwards to figure out why AllowAdministratorLockout is not present in these keys

**Comment by baristaTam** [comment]
'AllowAdministratorLockout' was missing from the baseline dictionaries in CISDSCResourceGeneration.psm1
I've added it to $script:AccountPolicySettings and now the resource is generated without errors! There is very little info about this setting online because it is new. I used this Microsoft KB page to determine it was an AccountPolicy Setting and the value it should have: https://support.microsoft.com/en-us/topic/kb5020282-account-lockout-available-for-built-in-local-administrators-bce45c4d-f28d-43ad-b6fe-70156cb2dc00

**Comment by edthedev** [comment]
Published to https://www.powershellgallery.com/packages/CISDSC/4.0.0
