### ISSUE TITLE
Exclude recommendation 5.3 from our Win11 resource

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecOps-Powershell-CISDSC#276]
##  Context

From #275 

              Per further investigation, we have confirmed that this is due to a mismatch between the intended recommendation (turn off a deprecated service) and the actual GPO Kit (turns off a similarly named, still relevant service).

@baristaTam  will put in a ticket with CIS requesting a correction.

As a follow-up, we should exclude this from our final definition for Win 11. (And possibly others.)

_Originally posted by @edthedev in https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/275#issuecomment-1967569559_
            
Task List:

- [ ] Exclude recommendation 5.3 from our final definition for Win 11
- [ ] Verify if others are affected
- [ ] IF AFFECTED, exclude from those as well

**Comment by mpitcel** [comment]
@edthedev ,  Question: Is this task list thorough enough?
