### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by alitavakoli-moonfare** [techservicesillinois/SecOps-Powershell-CISDSC#279]
Is it possible to use CISDSC for Windows 7?

**Comment by edthedev** [comment]
@alitavakoli-moonfare Current included Windows builds are listed here (not including Windows 7):
https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/tree/main/src/CISDSC/dscresources

I'm currently not aware of any core maintainer who intends to add Windows 7.

That said, a pull request adding Windows 7 could be created by following this guide:
https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/blob/main/CONTRIBUTING.md

Closing this as answered, but will re-open if a relevant pull request is submitted.
