### ISSUE TITLE
Is there anywhere in the PSDoc string thingies where we can add this so that a Get-Help will reveal this comment?

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/SecOps-Powershell-CISDSC#98]
Is there anywhere in the PSDoc string thingies where we can add this so that a Get-Help will reveal this comment?

_Originally posted by @edthedev in https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/pull/96#discussion_r488226907_

**Comment by edthedev** [comment]
If you look at the other comments in #96  - we identified a few other comments that could be valuable to pull out into the docstring at the start.

**Comment by MKletz** [comment]
Resolved in mentioned PR
